// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7jTgJo9DOJLzKDokfHQu0BGGJJBe_zM',
    appId: '1:539112737552:web:c487b83399738c746e7395',
    messagingSenderId: '539112737552',
    projectId: 'cloudfirestore-36d86',
    authDomain: 'cloudfirestore-36d86.firebaseapp.com',
    storageBucket: 'cloudfirestore-36d86.appspot.com',
    measurementId: 'G-1ST5VZ19SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-i1fw_su-WLBob_Y1aI7h85quXEROeT0',
    appId: '1:539112737552:android:87a846557ca469596e7395',
    messagingSenderId: '539112737552',
    projectId: 'cloudfirestore-36d86',
    storageBucket: 'cloudfirestore-36d86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3WKjs1Pj2UhviUN7fO2HrLD4wCP39juA',
    appId: '1:539112737552:ios:e04cdab5e7dc3e876e7395',
    messagingSenderId: '539112737552',
    projectId: 'cloudfirestore-36d86',
    storageBucket: 'cloudfirestore-36d86.appspot.com',
    iosBundleId: 'com.example.todoClud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3WKjs1Pj2UhviUN7fO2HrLD4wCP39juA',
    appId: '1:539112737552:ios:0ec27dbaa5477cb16e7395',
    messagingSenderId: '539112737552',
    projectId: 'cloudfirestore-36d86',
    storageBucket: 'cloudfirestore-36d86.appspot.com',
    iosBundleId: 'com.example.todoClud.RunnerTests',
  );
}
